import {
  Droplets, Zap, Paintbrush, LayoutGrid, Flower, Hammer, Tv, Snowflake, Wrench, Laptop,
  Smartphone, Bike, Car, Scissors, Utensils, Pill, ShoppingBag, Flame, Camera,
  Truck, Sparkles, Building, Package, FileText, Home, Heart, Store, Flower2,
  ChefHat, Leaf, ShoppingCart, Music, Shirt, Smile, Sliders, Activity, Mic
} from "lucide-react-native";

export const CATEGORIES = {
  HOME_MAINTENANCE: "Home Maintenance & Repairs",
  VEHICLES_PERSONAL: "Vehicles & Personal Care",
  LOGISTICS_BUSINESS: "Logistics & Business",
  EVENTS_SUPPLIES: "Events & Supplies"
};

export const CATEGORY_ICONS = {
  [CATEGORIES.HOME_MAINTENANCE]: Home,
  [CATEGORIES.VEHICLES_PERSONAL]: Smile,
  [CATEGORIES.LOGISTICS_BUSINESS]: Truck,
  [CATEGORIES.EVENTS_SUPPLIES]: Sparkles
};

// Local Bundled Native Image Assets
const SERVICE_IMAGES = {
  plumbing: require('../assets/services/plumbing.png'),
  electrical: require('../assets/services/electrical.png'),
  painting: require('../assets/services/painting.png'),
  tilesWork: require('../assets/services/tiles_work.png'),
  flowerDecor: require('../assets/services/flower_decor.png'),
  carpentry: require('../assets/services/carpentry.png'),
  appliance: require('../assets/services/appliance.png'),
  acRepair: require('../assets/services/ac_repair.png'),
  systemService: require('../assets/services/system_service.png'),
  carBooking: require('../assets/services/car_booking.png'),
  hairSalon: require('../assets/services/hair_salon.png'),
  foodDelivery: require('../assets/services/food_delivery.png'),
  medicineDelivery: require('../assets/services/medicine_delivery.png'),
  vegetableDelivery: require('../assets/services/vegetable_delivery.png'),
  groceryDelivery: require('../assets/services/grocery_delivery.png'),
  photoShoot: require('../assets/services/photo_shoot.png'),
  weldingWorks: require('../assets/services/welding_works.png'),
  houseShifting: require('../assets/services/house_shifting.png'),
  homeCleaning: require('../assets/services/home_cleaning.png'),
  officeCleaning: require('../assets/services/office_cleaning.png'),
  docBroker: require('../assets/services/document_broker.png'),
  realEstate: require('../assets/services/real_estate.png'),
  tailor: require('../assets/services/tailor_stitching.png'),
  mallBooking: require('../assets/services/mall_booking.png'),
  catering: require('../assets/services/catering.png'),
  bikeMechanic: require('../assets/services/bike_mechanic.png'),
  carMechanic: require('../assets/services/car_mechanic.png'),
  carWashing: require('../assets/services/car_washing.png'),
  tvRepair: require('../assets/services/tv_repair.png'),
  bikeWashing: require('../assets/services/bike_washing.png'),
  // Unique images for services that previously shared assets
  mobileService: require('../assets/services/mobile_service.png'),
  roPurifier: require('../assets/services/ro_purifier.png'),
  loadingService: require('../assets/services/loading_service.png'),
  unloadingService: require('../assets/services/unloading_service.png'),
  weddingEvent: require('../assets/services/wedding_event.png'),
  autoBooking: require('../assets/services/auto_booking.png'),
  drumsBand: require('../assets/services/drums_band.png'),
  dressRental: require('../assets/services/dress_rental.png'),
  welcomeStaff: require('../assets/services/welcome_staff.png'),
  djService: require('../assets/services/dj_service.png'),
  danceTroupe: require('../assets/services/dance_troupe.png'),
  liveSingers: require('../assets/services/live_singers.png'),
  vegetablesWholesale: require('../assets/services/vegetables_wholesale.png'),
  flowerStage: require('../assets/services/flower_decor.png'), // reusing closest match
};

export const ALL_SERVICES = [
  // CATEGORY 1: Home Maintenance & Repairs
  {
    name: "Plumbing Services",
    slug: "plumbing",
    desc: "Leak repairs, tap installations & piping.",
    icon: Droplets,
    image: SERVICE_IMAGES.plumbing,
    color: "#60a5fa",
    colorDark: "#2563eb",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Tap, mixer, and shower installation", "Pipe blockages & leak detection", "Bathroom fitting replacements", "30-day post-service warranty"]
  },
  {
    name: "Electrical Services",
    slug: "electrical",
    desc: "Wiring, switchboard installation & safety checks.",
    icon: Zap,
    image: SERVICE_IMAGES.electrical,
    color: "#fbbf24",
    colorDark: "#d97706",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Switchboard and socket installation", "Ceiling fan mounting & repair", "House wiring and fuse diagnostic", "Certified local electricians"]
  },
  {
    name: "Painting Services",
    slug: "painting",
    desc: "Wall painting, primers & designer texture coats.",
    icon: Paintbrush,
    image: SERVICE_IMAGES.painting,
    color: "#f472b6",
    colorDark: "#db2777",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Professional wall painting", "Surface scraping and priming", "Premium paint supplies included", "Mess-free cleanup post job"]
  },
  {
    name: "Flooring & Tile Installation",
    slug: "tiles-work",
    desc: "Precision floor tiling & kitchen wall tiles.",
    icon: LayoutGrid,
    image: SERVICE_IMAGES.tilesWork,
    color: "#94a3b8",
    colorDark: "#475569",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Granite & ceramic floor laying", "Bathroom wall tile repair", "Grouting & tile polishing", "Exact square-foot estimates"]
  },
  {
    name: "Floral Decoration Services",
    slug: "flower-works",
    desc: "Exquisite floral arrangements & garlands.",
    icon: Flower,
    image: SERVICE_IMAGES.flowerDecor,
    color: "#fb7185",
    colorDark: "#e11d48",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Pooja room fresh marigold garlands", "Doorway thoranam decoration", "Custom floral backdrops", "Same-day fresh flowers supply"]
  },
  {
    name: "Carpentry & Woodwork Solutions",
    slug: "carpentry",
    desc: "Cabinet repair, wooden shelves & carpentry.",
    icon: Hammer,
    image: SERVICE_IMAGES.carpentry,
    color: "#f59e0b",
    colorDark: "#92400e",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Modular kitchen repairs", "Door latch & hinge installation", "Custom wooden shelving", "Furniture dismantling & assembly"]
  },
  {
    name: "TV & Display Repair",
    slug: "tv-mechanic",
    desc: "LED/LCD TV mounting, repair & setup.",
    icon: Tv,
    image: SERVICE_IMAGES.tvRepair,
    color: "#818cf8",
    colorDark: "#4f46e5",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["LED/LCD Wall mounting", "Soundbar and home theatre setup", "Internal circuit card diagnostics", "Genuine spare parts replacement"]
  },
  {
    name: "AC Repair & Servicing",
    slug: "ac-repair",
    desc: "AC cleaning, gas filling & compressor fix.",
    icon: Snowflake,
    image: SERVICE_IMAGES.acRepair,
    color: "#38bdf8",
    colorDark: "#0284c7",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Deep filter & coil cleaning", "Gas leak detection & top-up", "Diagnostics & component repair", "30-day post-service warranty"]
  },
  {
    name: "Refrigerator Servicing",
    slug: "fridge-mechanic",
    desc: "Single/double door refrigerator diagnostics.",
    icon: Wrench,
    image: SERVICE_IMAGES.appliance,
    color: "#22d3ee",
    colorDark: "#0891b2",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Cooling coil diagnostic", "Gas charging & thermostat swap", "Door gasket rubber sealing", "All major brands supported"]
  },
  {
    name: "RO Water Purifier Services",
    slug: "ro-mechanic",
    desc: "Water filter cartridge swap & leak fix.",
    icon: Droplets,
    image: SERVICE_IMAGES.roPurifier,
    color: "#2dd4bf",
    colorDark: "#0d9488",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["RO Membrane & filter cartridge swap", "TDS level calibration", "Booster pump repair", "Leakage seal fix"]
  },
  {
    name: "Computer & Laptop Services",
    slug: "system-service",
    desc: "OS installation, RAM upgrade & laptop repairs.",
    icon: Laptop,
    image: SERVICE_IMAGES.systemService,
    color: "#3b82f6",
    colorDark: "#1d4ed8",
    category: CATEGORIES.HOME_MAINTENANCE,
    price: "Visiting Charge: ₹199",
    features: ["Windows/Linux OS installation", "Laptop screen & keyboard replacement", "RAM & SSD speed upgrade", "Virus cleaning & thermal pasting"]
  },

  // CATEGORY 2: Vehicles & Personal Care
  {
    name: "Mobile Phone Repair",
    slug: "mobile-service",
    desc: "Screen replacement, software & mic repair.",
    icon: Smartphone,
    image: SERVICE_IMAGES.mobileService,
    color: "#c084fc",
    colorDark: "#7e22ce",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Display panel replacement", "Battery health diagnostic & swap", "Charging port repair", "Doorstep pickup & delivery"]
  },
  {
    name: "Two-Wheeler Mechanic Services",
    slug: "bike-mechanic",
    desc: "Engine tuning, oil change & brake diagnostics.",
    icon: Bike,
    image: SERVICE_IMAGES.bikeMechanic,
    color: "#34d399",
    colorDark: "#059669",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Engine oil & spark plug change", "Chain tightening & lubrication", "Brake shoe replacement", "General 2-wheeler servicing"]
  },
  {
    name: "Four-Wheeler Auto Services",
    slug: "car-mechanic",
    desc: "Brake service, engine tuning & dent fixing.",
    icon: Car,
    image: SERVICE_IMAGES.carMechanic,
    color: "#2563eb",
    colorDark: "#1e40af",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Multi-point car inspection", "Brake pad replacement & bleeding", "Engine oil change and filter swap", "Roadside breakdown assistance"]
  },
  {
    name: "Motorbike Foam Wash",
    slug: "bike-washing",
    desc: "High-pressure foam wash & chrome polishing.",
    icon: Droplets,
    image: SERVICE_IMAGES.bikeWashing,
    color: "#0ea5e9",
    colorDark: "#0369a1",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["High pressure water wash", "Foam body shampooing", "Chain cleaning & lube spray", "Tire polish & shine"]
  },
  {
    name: "Car Foam Wash & Detailing",
    slug: "car-washing",
    desc: "Deep foam wash, interior vacuuming & dashboard polish.",
    icon: Droplets,
    image: SERVICE_IMAGES.carWashing,
    color: "#0284c7",
    colorDark: "#075985",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Exterior snow foam shampoo wash", "Underbody pressure jet cleaning", "Interior seats vacuuming", "Dashboard & tyre dressing"]
  },
  {
    name: "Hair Styling & Salon at Home",
    slug: "hair-cut-beautician",
    desc: "Professional haircutting & grooming at home.",
    icon: Scissors,
    image: SERVICE_IMAGES.hairSalon,
    color: "#a855f7",
    colorDark: "#ec4899",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Precision haircut & beard styling", "Facial massage & skin grooming", "Hygienic single-use kits", "Doorstep home service"]
  },
  {
    name: "Express Food Delivery",
    slug: "food-delivery",
    desc: "Hot meal pickups and deliveries at your step.",
    icon: Utensils,
    image: SERVICE_IMAGES.foodDelivery,
    color: "#f97316",
    colorDark: "#c2410c",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Hot parcel pickup from any hotel", "Express insulated thermal bag delivery", "Cash on delivery available", "Real-time phone updates"]
  },
  {
    name: "Doorstep Pharmacy Delivery",
    slug: "medicine-delivery",
    desc: "Prescription drug pickups and deliveries.",
    icon: Pill,
    image: SERVICE_IMAGES.medicineDelivery,
    color: "#10b981",
    colorDark: "#047857",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Prescription pickup from local pharmacy", "Emergency doorstep medicine drop", "Verified genuine bill check", "Safe temperature-controlled transport"]
  },
  {
    name: "Fresh Farm Vegetable Delivery",
    slug: "vegetable-delivery",
    desc: "Fresh, handpicked organic farm vegetables.",
    icon: ShoppingBag,
    image: SERVICE_IMAGES.vegetableDelivery,
    color: "#22c55e",
    colorDark: "#15803d",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Daily fresh market vegetables pickup", "Handpicked quality check", "Clean eco bag packaging", "Doorstep morning delivery"]
  },
  {
    name: "Professional Photography Services",
    slug: "photo-shoot",
    desc: "Event, portrait & family photography.",
    icon: Camera,
    image: SERVICE_IMAGES.photoShoot,
    color: "#8b5cf6",
    colorDark: "#6d28d9",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Pro DSLR cameraman hire", "Outdoor portrait & birthday shoots", "Color edited high-res digital album", "Raw video clips delivery"]
  },
  {
    name: "Precision Metal & Gate Welding",
    slug: "welding-works",
    desc: "Metal gate, window grill & railing repairs.",
    icon: Flame,
    image: SERVICE_IMAGES.weldingWorks,
    color: "#eab308",
    colorDark: "#a16207",
    category: CATEGORIES.VEHICLES_PERSONAL,
    price: "Visiting Charge: ₹199",
    features: ["Iron gate & latch welding", "Window grill fabrication repair", "Railing reinforcement", "On-site heavy arc welding machine"]
  },

  // CATEGORY 3: Logistics & Business
  {
    name: "House Shifting & Packers",
    slug: "house-shifting",
    desc: "Safe packing & moving with expert handlers.",
    icon: Truck,
    image: SERVICE_IMAGES.houseShifting,
    color: "#38bdf8",
    colorDark: "#0284c7",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Multi-layered bubble wrapping", "Heavy cardboard moving boxes", "Experienced loaders and drivers", "Safe transit insurance coverage"]
  },
  {
    name: "Deep House Cleaning",
    slug: "home-cleaning",
    desc: "Kitchen deep scrubbing & full house sanitizing.",
    icon: Sparkles,
    image: SERVICE_IMAGES.homeCleaning,
    color: "#10b981",
    colorDark: "#047857",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Full house deep vacuuming", "Bathroom stain & tile scrubbing", "Kitchen degreasing & appliance cleaning", "Safe eco-friendly chemicals"]
  },
  {
    name: "Commercial Office Cleaning",
    slug: "office-cleaning",
    desc: "Desks, glass panes and carpets cleaning.",
    icon: Building,
    image: SERVICE_IMAGES.officeCleaning,
    color: "#64748b",
    colorDark: "#334155",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Office floor scrubbing & buffing", "Workstation desk sanitization", "Glass partition wipe & polish", "Waste bin disposal & restock"]
  },
  {
    name: "Heavy Cargo & Parcel Loading",
    slug: "loading",
    desc: "Heavy machinery, furniture & box loading.",
    icon: Package,
    image: SERVICE_IMAGES.loadingService,
    colorDark: "#b45309",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Strong experienced manual labor team", "Heavy equipment loading ropes & belts", "Truck cargo arranging", "Safe damage-free handling"]
  },
  {
    name: "Unloading & Unpacking Services",
    slug: "unloading",
    desc: "Unpacking and placing heavy items safely.",
    icon: Package,
    image: SERVICE_IMAGES.unloadingService,
    colorDark: "#b45309",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Careful truck unloading", "Room-by-room item placement", "Cardboard box opening assistance", "Staircase heavy lifting"]
  },
  {
    name: "Government Documentation Assistance",
    slug: "govt-document-broker",
    desc: "Assistance with files, licenses & applications.",
    icon: FileText,
    image: SERVICE_IMAGES.docBroker,
    color: "#71717a",
    colorDark: "#3f3f46",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["RTO & Patta document verification", "Business license application help", "Form filling & xerox submission", "Doorstep file collection & delivery"]
  },
  {
    name: "Real Estate & Property Consultancy",
    slug: "real-estate-mediator",
    desc: "Plot, rental, and commercial properties search.",
    icon: Home,
    image: SERVICE_IMAGES.realEstate,
    color: "#059669",
    colorDark: "#047857",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Verified Hosur house rental search", "Commercial space & shop finding", "Plot site visits coordination", "Tenant & owner agreement assistance"]
  },
  {
    name: "Custom Tailoring & Stitching",
    slug: "tailor",
    desc: "Blouse stitching, alterations & custom fits at home.",
    icon: Scissors,
    image: SERVICE_IMAGES.tailor,
    color: "#ec4899",
    colorDark: "#be123c",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Designer blouse stitching", "Chudidhar & pant fitting alteration", "Doorstep measurement taking", "Delivered stitched to home"]
  },
  {
    name: "Wedding & Event Management",
    slug: "marriage-works",
    desc: "Wedding stage decor & ceremony planning.",
    icon: Heart,
    image: SERVICE_IMAGES.weddingEvent,
    price: "Visiting Charge: ₹199",
    features: ["Grand wedding mandapam stage decor", "Reception lighting setup", "Nadaswaram & welcome team coordination", "End-to-end event execution"]
  },
  {
    name: "Mall Event Space Booking",
    slug: "mall-booking",
    desc: "Promotional events space booking in malls.",
    icon: Store,
    image: SERVICE_IMAGES.mallBooking,
    color: "#6366f1",
    colorDark: "#4338ca",
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Mall atrium stall space booking", "Promotional banner permission", "Electrical plug & sound setup", "High footfall spot allocation"]
  },
  {
    name: "Custom Stage & Floral Design",
    slug: "flower-design",
    desc: "Exotic floral background and backdrop design.",
    icon: Flower2,
    image: SERVICE_IMAGES.flowerStage,
    category: CATEGORIES.LOGISTICS_BUSINESS,
    price: "Visiting Charge: ₹199",
    features: ["Fresh rose & jasmine flower stage backdrop", "Car flower decoration", "Reception entrance arch", "Custom flower color theme"]
  },

  // CATEGORY 4: Events & Supplies
  {
    name: "Catering & Buffet Services",
    slug: "catering-department",
    desc: "Multi-cuisine buffet & plate service.",
    icon: ChefHat,
    image: SERVICE_IMAGES.catering,
    color: "#f59e0b",
    colorDark: "#b45309",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Authentic South & North Indian menu", "Traditional banana leaf & buffet setup", "Experienced uniformed servers", "Hygienic live cooking counter"]
  },
  {
    name: "Premium Car Rentals",
    slug: "car-booking",
    desc: "Wedding and trip premium cars booking.",
    icon: Car,
    image: SERVICE_IMAGES.carBooking,
    color: "#3b82f6",
    colorDark: "#1d4ed8",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Luxury marriage car rental", "Outstation & local driver hire", "Clean sanitized AC sedans & SUVs", "Fixed per-km / day rate"]
  },
  {
    name: "Auto Rickshaw Hire",
    slug: "auto-booking",
    desc: "Goods and passenger auto hire.",
    icon: Truck,
    image: SERVICE_IMAGES.autoBooking,
    colorDark: "#854d0e",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Doorstep passenger auto arrival", "Luggage & goods auto transport", "Friendly verified local drivers", "Instant meter / fixed fare"]
  },
  {
    name: "Wholesale Fresh Vegetables Supply",
    slug: "vegetables-wholesale",
    desc: "Bulk vegetables supply for functions & hotels.",
    icon: Leaf,
    image: SERVICE_IMAGES.vegetablesWholesale,
    colorDark: "#14532d",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Mandi direct fresh vegetable supply", "Bulk wholesale pricing for marriages", "Cleaned & sorted gunny bags", "Early morning function site delivery"]
  },
  {
    name: "Wholesale Grocery & Provisions",
    slug: "grocery-wholesale",
    desc: "Bulk grains, oil & pantry provisions.",
    icon: ShoppingCart,
    image: SERVICE_IMAGES.groceryDelivery,
    color: "#0d9488",
    colorDark: "#115e59",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Rice bags, dal, oil drums wholesale", "Catering function bulk grocery kit", "Branded premium quality items", "Doorstep vehicle drop"]
  },
  {
    name: "Traditional Drums & Band Troupe",
    slug: "drums",
    desc: "Traditional drums & band sets for events.",
    icon: Music,
    image: SERVICE_IMAGES.drumsBand,
    colorDark: "#78350f",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Traditional Chenda melam & Dhol troupe", "Procession drum beats & brass band", "Energetic uniform performers", "Temple & wedding function booking"]
  },
  {
    name: "Bridal & Event Apparel Rentals",
    slug: "dress-rental",
    desc: "Wedding & ceremonial dress rentals.",
    icon: Shirt,
    image: SERVICE_IMAGES.dressRental,
    colorDark: "#4c1d95",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Designer wedding sherwani & lehenga rental", "Traditional silk saree & suit sets", "Dry-cleaned & sanitized outfits", "Trial fitting before event"]
  },
  {
    name: "Event Guest Welcoming & Hospitality Staff",
    slug: "welcome-givers",
    desc: "Event hostess and greeter staff hire.",
    icon: Smile,
    image: SERVICE_IMAGES.welcomeStaff,
    price: "Visiting Charge: ₹199",
    features: ["Saree-clad welcoming hostesses", "Aarthi, rose water & flower ushering", "Professional & polite event staff", "Full function duration service"]
  },
  {
    name: "DJ & Event Sound Systems",
    slug: "dj-service",
    desc: "High-power sound system, DJ console & stage lights.",
    icon: Sliders,
    image: SERVICE_IMAGES.djService,
    colorDark: "#6d28d9",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Pro DJ sound system setup", "LED ambient party light rigs", "Experienced local DJ artist", "Custom Tamil, Hindi & Kannada track mix"]
  },
  {
    name: "Dance Troupe & Choreography",
    slug: "dance-program",
    desc: "Choreographed troupe performances.",
    icon: Activity,
    image: SERVICE_IMAGES.danceTroupe,
    colorDark: "#881337",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Cinematic & folk dance troupe hire", "Stage costume & prop setups", "High-energy 1-2 hour show", "Marriage & festival celebrations"]
  },
  {
    name: "Live Singers & Orchestra Band",
    slug: "singers-vocalists",
    desc: "Melodious live vocalists and orchestra.",
    icon: Mic,
    image: SERVICE_IMAGES.liveSingers,
    colorDark: "#1e3a8a",
    category: CATEGORIES.EVENTS_SUPPLIES,
    price: "Visiting Charge: ₹199",
    features: ["Live orchestra & light music band", "Male & female professional singers", "Sound console & mic setup included", "Custom song requests welcome"]
  }
];
